[package]
name = "rfunge"
version = "0.1.0"
authors = ["Thomas Jollans <tjol@tjol.eu>"]
edition = "2018"
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divrem = "1.0"
num = "0.4"
clap = "2.33"
regex = "1.5"

[dev-dependencies]
colored = "2.0"

[[test]]
name = "test_examples"
harness = false